 [book]
title = "Lovecanon's Blog"
authors = ["Lovecanon"]
description = "Lovecanon's Blog"
language = "zh"
multilingual = false
src = "."

[build]
build-dir = "book"

[output.html]
mathjax-support = true
default-theme = "rust"

[output.html.search]
enable = true

[output.html.print]
enable = false
